### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by cvionis** [cvionis/typeracer-bot#1]
- [x] Prevent ElementNotInteractableException from occurring and browser from closing after race is completed 

- [x] Remove "word delay" variable and implement something smarter and easier to understand in its place

- [ ] Add support for more browsers
